index:
    path: /{_locale}
    controller: App\Controller\DefaultController::index
    defaults:
        _locale: fr
    requirements:
        _locale: en|fr

contributors:
    path: /{_locale}/contributors
    controller: App\Controller\ContributorsController::index
    defaults:
        _locale: fr
    requirements:
        _locale: en|fr
